# 天气可选值: clear, cloudy, rain, fog
# 时间可选值: morning, noon, evening, night
weather:
  - type: "clear"
  - time: "morning"

scenario_layout:
  - id: "1-1"
    spawn: true
    blueprint: "vehicle.tesla.model3"
  
  - id: "1-2"
    spawn: false  # 显式不生成
    blueprint: "default"

  - id: "1-4"
    spawn: true
    blueprint: "vehicle.ford.mustang"

  - id: "1-5"
    spawn: true
    blueprint: "default"

  # id "1-3" 没有写在这里，所以代码会默认不生成